name: Golang - Compile

on:
  # The release workflow will call this workflow to build the binaries, so we
  # need to allow workflow triggers.
  workflow_call:
  push:
    branches:
      - "**"
    paths-ignore:
      - ".github/workflows/**"
      - ".gitignore"
      - "docs/**"
      - "README.md"

jobs:
  compile:
    strategy:
      matrix:
        goos: ["linux"]
        goarch: ["amd64", "arm64"]
    runs-on: "ubuntu-24.04"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: "build/.go-version"
      - name: "Run compile"
        run: |
          make "bin/${{ matrix.goos }}_${{ matrix.goarch }}/smuggle"
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: smuggle_${{ matrix.goos }}-${{ matrix.goarch }}
          path: bin/${{ matrix.goos }}_${{ matrix.goarch }}/smuggle
          retention-days: 1
